
services:
  - type: web
    name: intelligent-class-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    branch: main
    autoDeploy: true
